### ISSUE TITLE
require("unplugin-auto-import/webpack") is not a function

### ISSUE THREAD

**Issue by Hyphon** [antfu/unplugin-auto-import#42]
plugin doesnt works in vue-cli ~4.5.0 + vue ^2.6.11, project is generated by vue-cli's template 

```
require("unplugin-vue2-script-setup/webpack")({
  // everything is ok
}),
require("unplugin-auto-import/webpack")({
  // v0.4.8 throw error, v0.2.7 is ok 
})
```

**Comment by Hyphon** [comment]
v0.4.12 is ok now
